NAME: 'MACD Trend Strategy'
MODULE: 'macd'
CLASS: 'SimpleMACD'
INTERVAL: '1h'
PERIOD: 300
RISK_PC: 1.5
SIZING: 'risk'
PARAMETERS:
  ema_period: 200
  MACD_fast: 5
  MACD_slow: 19
  MACD_smoothing: 9
  
  # Exit level parameters
  RR: 1.5

WATCHLIST: [
  # 'EURUSD=X',
  "BTC-USD"
  ]
            # 'EURJPY=X',
            # 'EURAUD=X',
            # 'AUDJPY=X']
            